#!/bin/sh
# Starts the exported game. Release builds of Godot don't accept --main-pack;
# they load block-party-skyway.pck from beside the binary on their own.
exec "$SNAP/game/block-party-skyway" "$@"
